### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by karthequian** [HewlettPackard/gas#44]
Hello,

I love this tool! However, what's the license on this?

**Comment by gcmurphy** [comment]
It is listed in the license file - https://github.com/HewlettPackard/gas/blob/master/LICENSE.txt

**Comment by karthequian** [comment]
DOH! Thanks! 👍

**Comment by callidus** [comment]
beat me to it :P

**Comment by gcmurphy** [comment]
No worries. We need to give the docs a bit of an update anyway. I'll look at including the license information in the main README.md
