### ISSUE TITLE
tests of subdirectories are not skipped

### ISSUE THREAD

**Issue by zyzjaffery** [HewlettPackard/gas#50]
I am using Mac. By looking at the source code, the '*_test.go' is in skip patterns by default.
However it doesn't work for tests in subdirectories (at least this is the case in Mac).

For example, if I run 'gas ./...' under /Users/xxx/Workspace/goprojects/src/a
then the results of the three patterns used in filelist.go are:

pathname:  /Users/xxx/Workspace/goprojects/src/a/b/timeTransformer_test.go
pattern 1: \*_test.go - not matched
pattern 2: /Users/xxx/Workspace/goprojects/src/a/\*_test.go - not matched
pattern 3: \*\*/\*_test.go - not matched

I think the quick fix is to make the third pattern join 'cwd' as well
`// match file suffixes ie. *_test.go
if matched, _ := filepath.Match(filepath.Join(cwd, "**", pattern), pathname); matched {`

I've tested then the test in subdirectories is skip.

**Comment by arekkas** [comment]
I can confirm this on windows, see #51
